name = "ExtensionExtensionReproducer"
uuid = "3f2f4494-4857-4fb4-9d20-87b554c3efb7"
authors = ["jumerckx <julesmerckx12@gmail.com>"]
version = "0.1.0"

[deps]
CalculusWithJulia = "a2e0e22d-7d4c-5312-9169-8b992201a882"

[weakdeps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
MyExt = "Plots"

[compat]
CalculusWithJulia = "0.2.8"
Plots = "1.40.9"
